---
platform: linux
image_resource:
  type: docker-image
  source: { repository: quay.io/desource/alpine, tag: build }

run:
  path: src/build.sh
    
inputs:
  - name: src
  - name: libressl
  - name: liblua
  - name: libslz

outputs:
  - name: out
  
